# Generated by Django 4.1.4 on 2022-12-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('productprice', models.CharField(max_length=10)),
                ('productimage', models.FileField(default='media/samsung.jfif', upload_to='media/images')),
                ('productmodel', models.CharField(max_length=10)),
                ('productram', models.CharField(max_length=10)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_shop.user')),
            ],
        ),
    ]
