# Generated by Django 4.1.4 on 2022-12-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_shop', '0002_productsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='productid',
            field=models.CharField(max_length=5),
        ),
    ]
