# Generated by Django 4.1.4 on 2023-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_shop', '0004_alter_productsubcategory_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='productimage',
            field=models.FileField(blank='true', default='media/samsung_mobile.jpg', null=True, upload_to='media/images'),
        ),
    ]
