# Generated by Django 4.1.4 on 2023-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_shop', '0005_alter_productsubcategory_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='productid',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='productimage',
            field=models.FileField(blank=True, default='media/samsung_mobile.jpg', null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='productmodel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='productname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='productprice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='productram',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
